### ISSUE TITLE
Tests don't pass on Linux

### ISSUE THREAD

**Issue by Bouke** [Bouke/Glob#7]
The tests fail with warnings similar to this:

> `/home/travis/build/Bouke/Glob/Tests/GlobTests/GlobTests.swift:250: error: GlobTests.testDoubleGlobstarGradle : XCTAssertEqual failed: ("["/tmp/7E28C42C-1C57-4784-B90F-BC1E91C814C0/dir1//dir2/dir3//file2.ext"]") is not equal to ("["/tmp/7E28C42C-1C57-4784-B90F-BC1E91C814C0/dir1/dir2/dir3/file2.ext"]")`

Not sure what's happening. There are additional path separators, but where are those coming from?

**Comment by xareelee** [comment]
Hi, how to run tests in command line without using Xcode?

**Comment by xareelee** [comment]
It passed on my Mac, but I did not run the tests on Linux.

I read the code and I guess that [`NSString(string: directory).appendingPathComponent(lastPart)`](https://github.com/Bouke/Glob/blob/1.0.4/Sources/Glob/Glob.swift#L153) doesn't well handle the two strings ,`/{expanded_Globstar_directory_path}/` and `/{lastPart}` on Linux. The SDK might be re-written for Linux.

The `lastPart` in code is prefixed with `"/"` because of [`pattern.components(separatedBy: "**")`](https://github.com/Bouke/Glob/blob/1.0.4/Sources/Glob/Glob.swift#L120) when expanding double glob stars. 

Maybe using `-URL.appendingPathComponent()` instead of `-NSString.appendingPathComponent` might solve the problem.

**Comment by Bouke** [comment]
I've reported the issue under [SR-13993](https://bugs.swift.org/browse/SR-13993). I've added a workaround in #13.
